---

 - name: Backup local path User windows
   hosts: Username
  
   tasks:
   - name:  C:\Windows\backup\1
     ansible.windows.win_file:
      path: C:\Windows\backup\1
      state: directory
      
   - name: Copy C:\Users to share Z:\
     ansible.windows.win_shell: Copy-Item C:\Users -Recurse Z:\backups\


