---
  - name: Configure ubuntu zabbix (docker)
    hosts: docker
    tasks:
      - block:
        - name: update && upgrade
          ansible.builtin.shell:
            cmd: apt update && apt -y upgrade

        - name: install wget
          ansible.builtin.apt:
            name: wget
            state: present  

        - name: install zabbix agent 2
          ansible.builtin.apt:
            deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb

        - name: install zabbix-agent2
          ansible.builtin.apt:
            name: zabbix-agent2
            state: present
            
        - name: install zabbix-agent2-plugin
          ansible.builtin.apt:
            name: zabbix-agent2-plugin-*
            state: present

        - name: Config zabbix.conf Server=
          ansible.builtin.lineinfile:
            path: /etc/zabbix/zabbix_agent2.conf
            search_string: Server=127.0.0.1
            line: Server=ipserver/24

        - name: Config zabbix.conf ServerActive=
          ansible.builtin.lineinfile:
            path: /etc/zabbix/zabbix_agent2.conf
            search_string: ServerActive=127.0.0.1
            line: ServerActive=ipserver

        - name: Config zabbix.conf Listenport=
          ansible.builtin.lineinfile:
            path: /etc/zabbix/zabbix_agent2.conf
            search_string: '# ListenPort=10050'
            line: ListenPort=10050

        - name: Change permission docker.sock # если используется мониторинг контейнеров
          ansible.builtin.file:
            path: /var/run/docker.sock
            owner: root
            group: docker
            mode: '0666'

        - name: enable and restart
          service:
            name: zabbix-agent2
            state: started
            enabled: yes
        when:  (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "22.04")
        
        rescue:

        - name: Print a message
          ansible.builtin.debug:
            msg: 'OS does not match'
