---
  - name: Configure ubuntu
    hosts: cloud
    become: true
    tasks:

      - name: update && upgrade
        ansible.builtin.shell:
          cmd: apt update && apt -y upgrade

      - name: install chrony
        ansible.builtin.apt:
          name: chrony
          state: present

      - name: install wget
        ansible.builtin.apt:
          name: wget
          state: present
      
      - name: install unzip
        ansible.builtin.apt:
          name: unzip
          state: present

      - name: install python3-pip
        ansible.builtin.apt:
          name: python3-pip
          state: present 
      
      - name: Enabling/restarting services chrony
        service:
          name: chrony
          state: started
          enabled: yes

      - name: set timedata
        ansible.builtin.shell:
          cmd: timedatectl set-timezone Europe/Moscow

      - name: iptables open 80 443
        ansible.builtin.shell:
          cmd: iptables -I INPUT -p tcp --dport 80 -j ACCEPT && iptables -I INPUT -p tcp --dport 443 -j ACCEPT

      - name: install iptables-persistent
        ansible.builtin.apt:
          name: iptables-persistent
          state: present

      - name: iptables save
        ansible.builtin.shell:
          cmd: netfilter-persistent save

      - name: install mariadb
        ansible.builtin.apt:
          name: mariadb-server-10.6
          state: present

      - name: Enabling/restarting services
          service:
            name: mariadb
            state: started
            enabled: yes

      - name: install apache2
        ansible.builtin.apt:
          name: apache2
          state: present 

      - name: export php
        ansible.builtin.shell:
          cmd: export PHP_VER=8.2

      - name: install php & co
        ansible.builtin.shell:
          cmd: apt install php php-fpm php-common php-zip php-xml php-intl php-gd php-mysql php-mbstring php-curl php-imagick libapache2-mod-fcgid php-gmp php-bcmath libmagickcore-6.q16-6-extra


